### ISSUE TITLE
Cannot see server in game

### ISSUE THREAD

**Issue by chunga168** [ihadeed/pavlov-vr-server#1]
Hi,

Firstly, thank you for building this, which makes the whole complicated process of hosting own server, a much easier job. Good job!
I followed your instructions and can see the server via https://pablub.club/, but can't seem to be able to see it in game.
Not sure if that's something I missed.

Looking through the page http://wiki.pavlov-vr.com/index.php?title=Dedicated_server, I can see that default port is 7777, and not 7500, so I did add that into game.ini.
I also noticed it mention you need to also expose +400 port, so I mapped out port 7900 too. But that didn't seem to work either.

Appreciate if anyone can help. I'm trying to play the game with my friends in Hong Kong, but there's no server around, so we have to play with high pings. Be good if we can successfully host our own server (unfortunately we don't have Linux servers so containerized is our best solution).

Thanks! Let me know if you'd like me to provide any logs.

**Comment by ihadeed** [comment]
Hey!

Just updated docker-compose to show the correct usage: https://github.com/ihadeed/pavlov-vr-server/blob/master/docker-compose.yml

The container requires that you pass it the port in environment variables; then you have to bind ports to your host network based on that.

The docker compose is now setup to start a server on port 7500. So it's forwarding UDP packets for ports 7500 and 7900. The equivalent `docker run` command would be:
```shell
docker run --name pavlov -d \
-p 7500:7500/udp \
-p 7900:7900/udp \
-e PORT=7500 \
-v $(pwd)/Game.ini:/home/steam/pavlovserver/Pavlov/Saved/Config/LinuxServer/Game.ini \
ihadeed/pavlov-server
```

I also added an example `RconSettings.txt` file and configured it in docker-compose.yml. You can see I'm also binding the `15200/tcp` port so I can access Rcon remotely.

**Comment by chunga168** [comment]
Thank you sir! you're awesome! it's all working now... I had some confusion but I realised the "hide empty" filter was switched on by default, but can join my server right after i turned that off... Thank you thank you for simplifying something so complicated for someone like me!
